### ISSUE TITLE
Android: View.getParent() on a null object reference

### ISSUE THREAD

**Issue by StevenMasini** [prscX/react-native-tooltips#12] opened 2018-09-12 03:32 UTC
Hi @prscX 

I found out a crash on Android when the `reference` props provided on the javascript side has not been acknowledged yet by react native.

In react native, references to component are only known after the first call to the render method.

On Android when `final ViewGroup target = activity.findViewById(view);` receive an non-existent id, `target` will then be null. Of course null object don't have access to the method `getParent` and will trigger an exception.

On iOS I suppose that's not an issue as the method `presentFromView` might be protected from receiving `Nil`.

I will submit a Pull Request that fix this issue for Android.

**Comment by prscX** [comment] 2018-09-12 11:44
Thanks @StevenMasini for reporting the issue and sharing the detailed root cause.

I have merged the PR.

Thanks
</ Pranav >

**Comment by StevenMasini** [comment] 2018-09-14 06:35
I think we can close this issue.

**Comment by prscX** [comment] 2018-09-14 06:44
Thanks @StevenMasini. Closed 😄 

Thanks
</ Pranav >

**Closed by prscX** 2018-09-14 06:44 UTC
